site_name: cybergisx-cli

repo_url: https://github.com/cybergis/cybergisx-cli

theme:
    name: material
    features:
        - navigation.instant
        - search.highlight

nav:
  - Home: 'index.md'
  - 'User Guide':
    - 'cybergisx': 'cybergisx.md'
    - 'cjw': 'cjw.md'